### PR TITLE
C10-3-Desarrollo vista desktop home blog

### PR DESCRIPTION
**Pull request by FranCalderon67**

### CODE REVIEW

**Comment by FranCalderon67** [comment]
https://criptopro.atlassian.net/jira/software/projects/C10/boards/6?selectedIssue=C10-3

**Review by criptopromanagement — APPROVED** [review]
LGTM!

**Review by criptopromanagement — CHANGES_REQUESTED** [review]
<html>
<body>


./src/components/home/home-blog-desktop.tsx
--
11:41:35.936 | 66:21  Error: Missing "key" prop for element in iterator  react/jsx-key


</body>
</html>

**Review by criptopromanagement — APPROVED** [review]
Excelente trabajo Fran!

**Pull request merged**
